### ISSUE TITLE
quiz

### ISSUE THREAD

**Issue by valuestay** [yctung/LibAcousticSensing#24]
How can I use LibAS to develop my own project？Does LibAS  have app  on Android or Windows?

**Comment by ducalpha** [comment]
According the [License](https://github.com/yctung/LibAcousticSensing/blob/master/LICENSE.txt), you can develop your project based on LibAS.

The source code of an Android app is included here: https://github.com/yctung/LibAcousticSensing/tree/master/DevApp/Android
